import './globals.css'
// import Provider from '@/components/Provider'
import Nav from "@/components/Nav";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className="p-5">
        {/*<Provider>*/}
            <Nav></Nav>
            {children}
        {/*</Provider>*/}
        </body>
        </html>
    )
}
